### ISSUE TITLE
How to Generate API token?

### ISSUE THREAD

**Issue by surajdalvi** [julianlam/nodebb-plugin-write-api#12]
How to Generate uid an API token in the ACP page please help me?

**Comment by surajdalvi** [comment]
I install nodebb-plugin-write-api these plugin in nodeBB but i get following error?


 error: [plugins] Error executing 'static:app.load' in plugin
'nodebb-plugin-write-api'
 - error:  Error: Route.post() requires callback functions but g
ot a [object Undefined]
    at Route.<anonymous> (D:\d\NodeBB\node_modules\nodebb-plugin-write-api\node_
modules\express\lib\router\route.js:170:15)
    at Array.forEach (native)
    at Route.(anonymous function) [as post] (D:\d\NodeBB\node_modules\nodebb-plu
gin-write-api\node_modules\express\lib\router\route.js:166:15)
    at Function.proto.(anonymous function) (D:\d\NodeBB\node_modules\nodebb-plug
in-write-api\node_modules\express\lib\router\index.js:498:19)
    at module.exports (D:\d\NodeBB\node_modules\nodebb-plugin-write-api\routes\v
1\groups.js:22:6)
    at module.exports (D:\d\NodeBB\node_modules\nodebb-plugin-write-api\routes\v
1\index.js:10:40)
    at module.exports (D:\d\NodeBB\node_modules\nodebb-plugin-write-api\routes\i
ndex.js:7:26)
    at Object.API.init [as method] (D:\d\NodeBB\node_modules\nodebb-plugin-write
-api\index.js:14:34)
    at D:\d\NodeBB\src\plugins\hooks.js:127:14
    at D:\d\NodeBB\node_modules\async\lib\async.js:125:13




please help me?

**Comment by julianlam** [comment]
Hi @surajdalvi -- have you figured out this issue?
