### ISSUE TITLE
Error executing 'static:app.load'

### ISSUE THREAD

**Issue by atomoc** [julianlam/nodebb-plugin-write-api#15]
./nodebb dev output:
```
[plugins] Error executing 'static:app.load' in plugin 'nodebb-plugin-write-api'
6/4 18:44 [13770] - error:  Error: Cannot find module './public/src/translator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at Object.<anonymous> (/home/nodebb/node_modules/nodebb-plugin-write-api/lib/errorHandler.js:4:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by julianlam** [comment]
Update to latest write-api code.

**Comment by atomoc** [comment]
Thanks!
