### ISSUE TITLE
Plugin not Working  I get following error- Error executing 'static:app.load' in plugin 'nodebb-plugin-write-api'   please help me?

### ISSUE THREAD

**Issue by surajdalvi** [julianlam/nodebb-plugin-write-api#16]

**Comment by julianlam** [comment]
Need full stack trace with error.

**Comment by surajdalvi** [comment]
I got following error:


 -error: [plugins] Error executing 'static:app.load' in plugin
'nodebb-plugin-write-api'
-error:  Error: Cannot find module './public/src/modules/trans
lator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at Object.<anonymous> (D:\Final NodeBB\final\nodebb\node_modules\nodebb-plug
in-write-api\lib\errorHandler.js:4:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by surajdalvi** [comment]
Issue is solve it occour due one file is missing at './public/src/modules' location
