### ISSUE TITLE
Create api token does not work

### ISSUE THREAD

**Issue by robzhu** [julianlam/nodebb-plugin-write-api#5]
Hello, I am not able to create either uid or master tokens via the /admin/plugins/write-api page. Is there something I'm missing? 

Here are my configuration details;
-NodeBB running in docker connected to redis docker data volume (I have tried versions 0.5.4, and 0.6.1, and 0.7)
-plugin-write-api is the only plugin I have installed. 
-all other settings left as default

Have I missed a step?

**Comment by julianlam** [comment]
What kind of errors do you see when you click the button to create a token?

**Comment by robzhu** [comment]
No errors. The button just appears to do nothing.

**Comment by robzhu** [comment]
Would you like me to provide a clean installation and make you admin so you can see the repro?

**Comment by julianlam** [comment]
That could be useful. Thanks!

**Comment by robzhu** [comment]
Here you go:
http://104.131.48.69:4567
username: admin
password: password

I have not run any npm install scripts on the server, this is a completely clean installation of nodeBB 0.5.4 running inside a container (ubuntu), linked to a redis container (ubuntu) per these instructions:

https://docs.nodebb.org/en/latest/installing/docker/nodebb-redis.html

**Comment by robzhu** [comment]
Please let me know when you have confirmed the repro so that I can take the VM down.

**Comment by julianlam** [comment]
Hm, I can't seem to restart NodeBB after installing write-api, can you do that for me please?

**Comment by robzhu** [comment]
I just restarted it for you.

**Comment by julianlam** [comment]
Seems the package got uninstalled when you restarted, and now it's down again. v0.5.4 also is pretty old, can you give it a try with 0.6.1?

**Comment by robzhu** [comment]
Are you sure? It's up for me right now, and the write-api plugin shows up on the admin control panel. The dashboard also indicates it's now at 0.6.1

**Comment by julianlam** [comment]
Yep, accessing http://104.131.48.69:4567/ gives me a 404

**Comment by robzhu** [comment]
Sorry about that, you're right, it's down, I was looking at the tab for my local repro.

**Comment by robzhu** [comment]
The container is now in a bad state, trying to restart it yields the following error:

2015-03-05T16:43:13.203Z - info: NodeBB v0.5.4 Copyright (C) 2013-2014 NodeBB Inc.
2015-03-05T16:43:13.207Z - info: This program comes with ABSOLUTELY NO WARRANTY.
2015-03-05T16:43:13.208Z - info: This is free software, and you are welcome to redistribute it under certain conditions.
2015-03-05T16:43:13.209Z - info:
2015-03-05T16:43:13.214Z - info: Time: Thu Mar 05 2015 16:43:13 GMT+0000 (UTC)
2015-03-05T16:43:13.214Z - info: Initializing NodeBB v0.5.4
2015-03-05T16:43:13.214Z - info: * using configuration stored in: /opt/nodebb/config.json

2015-03-05T16:43:14.257Z - warn: [plugins/nodebb-plugin-markdown] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
2015-03-05T16:43:14.258Z - warn: [plugins/nodebb-plugin-markdown] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-plugin-markdown".


2015-03-05T16:43:14.260Z - warn: [plugins/nodebb-plugin-write-api] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
2015-03-05T16:43:14.261Z - warn: [plugins/nodebb-plugin-write-api] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-plugin-write-api".


2015-03-05T16:43:14.262Z - warn: [plugins/nodebb-plugin-mentions] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
2015-03-05T16:43:14.263Z - warn: [plugins/nodebb-plugin-mentions] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-plugin-mentions".


2015-03-05T16:43:14.264Z - warn: [plugins/nodebb-widget-essentials] This plugin may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing.
2015-03-05T16:43:14.264Z - warn: [plugins/nodebb-widget-essentials] In the event of an unresponsive NodeBB caused by this plugin, run ./nodebb reset plugin="nodebb-widget-essentials".

2015-03-05T16:43:14.483Z - error: TypeError: Cannot call method 'use' of undefined
    at Object.API.init (/opt/nodebb/node_modules/nodebb-plugin-write-api/index.js:15:14)
    at /opt/nodebb/src/plugins.js:489:23
    at /opt/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/opt/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/opt/nodebb/node_modules/async/lib/async.js:124:9)
    at Object.Plugins.fireHook (/opt/nodebb/src/plugins.js:487:12)
    at Plugins.reloadRoutes (/opt/nodebb/src/plugins.js:135:11)
    at /opt/nodebb/node_modules/async/lib/async.js:656:23
    at fn (/opt/nodebb/node_modules/async/lib/async.js:641:34)
TypeError: Cannot call method 'use' of undefined
    at Object.API.init (/opt/nodebb/node_modules/nodebb-plugin-write-api/index.js:15:14)
    at /opt/nodebb/src/plugins.js:489:23
    at /opt/nodebb/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/opt/nodebb/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/opt/nodebb/node_modules/async/lib/async.js:124:9)
    at Object.Plugins.fireHook (/opt/nodebb/src/plugins.js:487:12)
    at Plugins.reloadRoutes (/opt/nodebb/src/plugins.js:135:11)
    at /opt/nodebb/node_modules/async/lib/async.js:656:23
    at fn (/opt/nodebb/node_modules/async/lib/async.js:641:34)
2015-03-05T16:43:14.490Z - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2015-03-05T16:43:14.491Z - info: [app] Database connection closed.

net.js:1233
    throw new Error('Not running');
          ^
Error: Not running
    at Server.close (net.js:1233:11)
    at shutdown (/opt/nodebb/app.js:344:36)
    at process.<anonymous> (/opt/nodebb/app.js:181:7)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)

**Comment by julianlam** [comment]
Bad state due to incorrect NodeBB version. It's only compatible with v0.6.x, so can you please start over with that version please? :smile:

**Comment by robzhu** [comment]
Can you point me to a docker image/dockerfile that has 0.6.X?

**Comment by julianlam** [comment]
@xaoseric?

**Comment by robzhu** [comment]
https://github.com/xaoseric/nodebb-docker/blob/master/ubuntu/Dockerfile ?

That dockerfile results in a 0.7.0 nodeBB image.

**Comment by robzhu** [comment]
Ok, http://104.131.48.69:4567/admin is back up, on 0.6.1, with the write-api plugin installed.

**Comment by robzhu** [comment]
Here's the dockerfile (modified from @xaoseric):

# Pull base image.
FROM ubuntu:latest
MAINTAINER NodeBB Docker Team <docker-devs@nodebb.org>

ENV DEBIAN_FRONTEND noninteractive

# Install base packages
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install nodejs nodejs-legacy npm imagemagick git wget unzip -y

# Install nodebb
# RUN cd /opt && git clone https://github.com/NodeBB/NodeBB nodebb

RUN cd /opt && wget https://api.github.com/repos/NodeBB/NodeBB/zipball/v0.6.1 -O nodebb.zip && unzip nodebb.zip && mv NodeBB-NodeBB-2b3c8b7 nodebb && rm nodebb.zip
RUN cd /opt/nodebb && npm install

# Create a mountable volume
VOLUME /opt/nodebb

# Define working directory.
WORKDIR /opt/nodebb

# Expose ports
EXPOSE 80
EXPOSE 443
EXPOSE 4567

# Define default command.
CMD ["node", "app.js"]

**Comment by julianlam** [comment]
Thanks, confirmed on your instance and on my local dev, but only on `v0.6.x` branch. `master` is fine.

**Comment by robzhu** [comment]
Thanks, I'm taking the VM down since you have a local repro.

**Comment by julianlam** [comment]
Oddly, this only happens if the plugin is activated and then NodeBB is **reloaded**. If NodeBB is **restarted**, the problem is resolved (and subsequent reloads are fine as well).

Can you confirm?

**Comment by robzhu** [comment]
Is that on 0.6.1 or 0.7?

**Comment by julianlam** [comment]
0.6.1, not sure if 0.7.0 exhibits the same problem.

**Comment by xaoseric** [comment]
@robzhu It was grabbing the image from the 0.5.x branch, updated it to grab the image from the 0.6.x branch, once docker picks up on the changes on github, it should work.

**Comment by xaoseric** [comment]
@julianlam I'll check on 0.7.0 and see if it exhibits the same problem

**Comment by julianlam** [comment]
Closed due to inactivity -- please let me know if this issue persists.
